package decision

import (
	"context"
	"database/sql"
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"

	_ "modernc.org/sqlite"

	"basestealmodel/backend/internal/db"
)

// golden_fixtures.json is generated by src/export_golden_fixtures.py from
// the SAME predict_steal_decision Python function this package ports --
// see that script's docstring. Regenerate deliberately (like
// backend/data/app.db), not automatically.

type fixtureSituation struct {
	Inning                int      `json:"inning"`
	Half                  int      `json:"half"`
	Outs                  int      `json:"outs"`
	BaseCode              string   `json:"base_code"`
	ScoreDiff             int      `json:"score_diff"`
	Target                string   `json:"target"`
	Balls                 int      `json:"balls"`
	Strikes               int      `json:"strikes"`
	IsDoubleSteal         bool     `json:"is_double_steal"`
	RunnerBatsLHB         bool     `json:"runner_bats_lhb"`
	PitcherThrowsLHP      bool     `json:"pitcher_throws_lhp"`
	RunnerPriorSR         float64  `json:"runner_prior_sr"`
	RunnerPriorAtt        int      `json:"runner_prior_att"`
	PitcherPriorSRAllowed float64  `json:"pitcher_prior_sr_allowed"`
	CatcherPriorCSRate    float64  `json:"catcher_prior_cs_rate"`
	RunnerSprintSpeed     *float64 `json:"runner_sprint_speed"`
	RunnerAge             *float64 `json:"runner_age"`
	CatcherPopTime        *float64 `json:"catcher_pop_time"`
}

func (fs fixtureSituation) toSituation() Situation {
	return Situation{
		Inning: fs.Inning, Half: fs.Half, Outs: fs.Outs, BaseCode: fs.BaseCode,
		ScoreDiff: fs.ScoreDiff, Target: fs.Target, Balls: fs.Balls, Strikes: fs.Strikes,
		IsDoubleSteal:         fs.IsDoubleSteal,
		RunnerBatsLHB:         fs.RunnerBatsLHB,
		PitcherThrowsLHP:      fs.PitcherThrowsLHP,
		RunnerPriorSR:         fs.RunnerPriorSR,
		RunnerPriorAtt:        fs.RunnerPriorAtt,
		PitcherPriorSRAllowed: fs.PitcherPriorSRAllowed,
		CatcherPriorCSRate:    fs.CatcherPriorCSRate,
		RunnerSprintSpeed:     fs.RunnerSprintSpeed,
		RunnerAge:             fs.RunnerAge,
		CatcherPopTime:        fs.CatcherPopTime,
	}
}

type fixtureExpected struct {
	WinProbCurrent   float64  `json:"win_prob_current"`
	WinProbIfSuccess float64  `json:"win_prob_if_success"`
	BreakEven        float64  `json:"break_even"`
	PSuccess         float64  `json:"p_success"`
	Decision         string   `json:"decision"`
	Layer            string   `json:"layer"`
	MinN             float64  `json:"min_n"`
	LowConfidence    bool     `json:"low_confidence"`
	Sources          []string `json:"sources"`
}

type fixture struct {
	Input    fixtureSituation `json:"input"`
	Expected fixtureExpected  `json:"expected"`
	Note     string           `json:"note"`
}

func loadFixtures(t *testing.T) []fixture {
	t.Helper()
	path := filepath.Join("testdata", "golden_fixtures.json")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v (run: python -m src.export_golden_fixtures)", path, err)
	}
	var fixtures []fixture
	if err := json.Unmarshal(data, &fixtures); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	if len(fixtures) == 0 {
		t.Fatal("no fixtures loaded")
	}
	return fixtures
}

func loadRealTables(t *testing.T) (Tables, *Model, Medians) {
	t.Helper()
	dbPath := filepath.Join("..", "..", "data", "app.db")
	conn, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open %s: %v", dbPath, err)
	}
	t.Cleanup(func() { conn.Close() })

	q := db.New(conn)
	tables, model, medians, err := LoadAll(context.Background(), q)
	if err != nil {
		t.Fatalf("LoadAll: %v", err)
	}
	return tables, model, medians
}

const floatTolerance = 1e-6

func almostEqual(a, b float64) bool {
	return math.Abs(a-b) <= floatTolerance
}

func TestGoldenFixturesMatchPython(t *testing.T) {
	fixtures := loadFixtures(t)
	tables, model, medians := loadRealTables(t)

	gappedTables := tables
	gappedTables.RE24 = RE24Table{}

	for i, f := range fixtures {
		f := f
		t.Run(f.Input.BaseCode+"_"+f.Input.Target, func(t *testing.T) {
			useTables := tables
			if f.Note == "re24_gap" {
				useTables = gappedTables
			}

			got := PredictStealDecision(useTables, model, medians, f.Input.toSituation())
			want := f.Expected

			if !almostEqual(got.WinProbCurrent, want.WinProbCurrent) {
				t.Errorf("fixture %d: win_prob_current = %v, want %v", i, got.WinProbCurrent, want.WinProbCurrent)
			}
			if !almostEqual(got.WinProbIfSuccess, want.WinProbIfSuccess) {
				t.Errorf("fixture %d: win_prob_if_success = %v, want %v", i, got.WinProbIfSuccess, want.WinProbIfSuccess)
			}
			if !almostEqual(got.BreakEven, want.BreakEven) {
				t.Errorf("fixture %d: break_even = %v, want %v", i, got.BreakEven, want.BreakEven)
			}
			if !almostEqual(got.PSuccess, want.PSuccess) {
				t.Errorf("fixture %d: p_success = %v, want %v", i, got.PSuccess, want.PSuccess)
			}
			if got.DecisionLabel != want.Decision {
				t.Errorf("fixture %d: decision = %q, want %q", i, got.DecisionLabel, want.Decision)
			}
			if got.Layer != want.Layer {
				t.Errorf("fixture %d: layer = %q, want %q", i, got.Layer, want.Layer)
			}
			if got.LowConfidence != want.LowConfidence {
				t.Errorf("fixture %d: low_confidence = %v, want %v", i, got.LowConfidence, want.LowConfidence)
			}
			if !math.IsInf(want.MinN, 1) && !almostEqual(float64(got.MinN), want.MinN) {
				t.Errorf("fixture %d: min_n = %v, want %v", i, float64(got.MinN), want.MinN)
			}
			if len(got.Sources) != len(want.Sources) {
				t.Errorf("fixture %d: sources length = %d, want %d (got %v, want %v)",
					i, len(got.Sources), len(want.Sources), got.Sources, want.Sources)
			} else {
				for j := range got.Sources {
					if got.Sources[j] != want.Sources[j] {
						t.Errorf("fixture %d: sources[%d] = %q, want %q", i, j, got.Sources[j], want.Sources[j])
					}
				}
			}
		})
	}
}
