// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model.sql

package db

import (
	"context"
)

const getModelMeta = `-- name: GetModelMeta :one
SELECT intercept, median_runner_sprint_speed, median_runner_age, median_catcher_pop_time,
       trained_at, train_rows
FROM model_meta WHERE id = 1
`

type GetModelMetaRow struct {
	Intercept               float64 `json:"intercept"`
	MedianRunnerSprintSpeed float64 `json:"median_runner_sprint_speed"`
	MedianRunnerAge         float64 `json:"median_runner_age"`
	MedianCatcherPopTime    float64 `json:"median_catcher_pop_time"`
	TrainedAt               string  `json:"trained_at"`
	TrainRows               int64   `json:"train_rows"`
}

func (q *Queries) GetModelMeta(ctx context.Context) (GetModelMetaRow, error) {
	row := q.db.QueryRowContext(ctx, getModelMeta)
	var i GetModelMetaRow
	err := row.Scan(
		&i.Intercept,
		&i.MedianRunnerSprintSpeed,
		&i.MedianRunnerAge,
		&i.MedianCatcherPopTime,
		&i.TrainedAt,
		&i.TrainRows,
	)
	return i, err
}

const listModelCoefficients = `-- name: ListModelCoefficients :many
SELECT feature_name, sort_order, coefficient FROM model_coefficients ORDER BY sort_order
`

func (q *Queries) ListModelCoefficients(ctx context.Context) ([]ModelCoefficient, error) {
	rows, err := q.db.QueryContext(ctx, listModelCoefficients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelCoefficient
	for rows.Next() {
		var i ModelCoefficient
		if err := rows.Scan(&i.FeatureName, &i.SortOrder, &i.Coefficient); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
