// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Catcher struct {
	PlayerID       string          `json:"player_id"`
	FullName       string          `json:"full_name"`
	SearchName     string          `json:"search_name"`
	LastTeam       sql.NullString  `json:"last_team"`
	PriorCsRate    float64         `json:"prior_cs_rate"`
	PopTime        sql.NullFloat64 `json:"pop_time"`
	PopTimeMissing int64           `json:"pop_time_missing"`
	LastSeenDate   string          `json:"last_seen_date"`
}

type ModelCoefficient struct {
	FeatureName string  `json:"feature_name"`
	SortOrder   int64   `json:"sort_order"`
	Coefficient float64 `json:"coefficient"`
}

type ModelMetum struct {
	ID                      int64   `json:"id"`
	Intercept               float64 `json:"intercept"`
	MedianRunnerSprintSpeed float64 `json:"median_runner_sprint_speed"`
	MedianRunnerAge         float64 `json:"median_runner_age"`
	MedianCatcherPopTime    float64 `json:"median_catcher_pop_time"`
	TrainedAt               string  `json:"trained_at"`
	TrainRows               int64   `json:"train_rows"`
}

type Pitcher struct {
	PlayerID       string         `json:"player_id"`
	FullName       string         `json:"full_name"`
	SearchName     string         `json:"search_name"`
	LastTeam       sql.NullString `json:"last_team"`
	ThrowsLhp      int64          `json:"throws_lhp"`
	PriorSrAllowed float64        `json:"prior_sr_allowed"`
	LastSeenDate   string         `json:"last_seen_date"`
}

type Re24Cell struct {
	BaseCode     string  `json:"base_code"`
	Outs         int64   `json:"outs"`
	ExpectedRuns float64 `json:"expected_runs"`
}

type Runner struct {
	PlayerID           string          `json:"player_id"`
	FullName           string          `json:"full_name"`
	SearchName         string          `json:"search_name"`
	LastTeam           sql.NullString  `json:"last_team"`
	BatsLhb            int64           `json:"bats_lhb"`
	PriorSr            float64         `json:"prior_sr"`
	PriorAtt           int64           `json:"prior_att"`
	SprintSpeed        sql.NullFloat64 `json:"sprint_speed"`
	SprintSpeedMissing int64           `json:"sprint_speed_missing"`
	Age                sql.NullFloat64 `json:"age"`
	AgeMissing         int64           `json:"age_missing"`
	LastSeenDate       string          `json:"last_seen_date"`
}

type WinProbCell struct {
	TableKind    string  `json:"table_kind"`
	InningBucket int64   `json:"inning_bucket"`
	Half         int64   `json:"half"`
	Outs         int64   `json:"outs"`
	BaseCode     string  `json:"base_code"`
	ScoreBucket  int64   `json:"score_bucket"`
	WinRate      float64 `json:"win_rate"`
	N            int64   `json:"n"`
}
