// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"
	"database/sql"
)

const searchCatchers = `-- name: SearchCatchers :many
SELECT player_id, full_name, last_team, prior_cs_rate, pop_time, pop_time_missing
FROM catchers
WHERE search_name LIKE ?1
ORDER BY full_name
LIMIT ?2
`

type SearchCatchersParams struct {
	SearchName string `json:"search_name"`
	Limit      int64  `json:"limit"`
}

type SearchCatchersRow struct {
	PlayerID       string          `json:"player_id"`
	FullName       string          `json:"full_name"`
	LastTeam       sql.NullString  `json:"last_team"`
	PriorCsRate    float64         `json:"prior_cs_rate"`
	PopTime        sql.NullFloat64 `json:"pop_time"`
	PopTimeMissing int64           `json:"pop_time_missing"`
}

func (q *Queries) SearchCatchers(ctx context.Context, arg SearchCatchersParams) ([]SearchCatchersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchCatchers, arg.SearchName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCatchersRow
	for rows.Next() {
		var i SearchCatchersRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.FullName,
			&i.LastTeam,
			&i.PriorCsRate,
			&i.PopTime,
			&i.PopTimeMissing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPitchers = `-- name: SearchPitchers :many
SELECT player_id, full_name, last_team, throws_lhp, prior_sr_allowed
FROM pitchers
WHERE search_name LIKE ?1
ORDER BY full_name
LIMIT ?2
`

type SearchPitchersParams struct {
	SearchName string `json:"search_name"`
	Limit      int64  `json:"limit"`
}

type SearchPitchersRow struct {
	PlayerID       string         `json:"player_id"`
	FullName       string         `json:"full_name"`
	LastTeam       sql.NullString `json:"last_team"`
	ThrowsLhp      int64          `json:"throws_lhp"`
	PriorSrAllowed float64        `json:"prior_sr_allowed"`
}

func (q *Queries) SearchPitchers(ctx context.Context, arg SearchPitchersParams) ([]SearchPitchersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPitchers, arg.SearchName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPitchersRow
	for rows.Next() {
		var i SearchPitchersRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.FullName,
			&i.LastTeam,
			&i.ThrowsLhp,
			&i.PriorSrAllowed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRunners = `-- name: SearchRunners :many
SELECT player_id, full_name, last_team, bats_lhb, prior_sr, prior_att,
       sprint_speed, sprint_speed_missing, age, age_missing
FROM runners
WHERE search_name LIKE ?1
ORDER BY full_name
LIMIT ?2
`

type SearchRunnersParams struct {
	SearchName string `json:"search_name"`
	Limit      int64  `json:"limit"`
}

type SearchRunnersRow struct {
	PlayerID           string          `json:"player_id"`
	FullName           string          `json:"full_name"`
	LastTeam           sql.NullString  `json:"last_team"`
	BatsLhb            int64           `json:"bats_lhb"`
	PriorSr            float64         `json:"prior_sr"`
	PriorAtt           int64           `json:"prior_att"`
	SprintSpeed        sql.NullFloat64 `json:"sprint_speed"`
	SprintSpeedMissing int64           `json:"sprint_speed_missing"`
	Age                sql.NullFloat64 `json:"age"`
	AgeMissing         int64           `json:"age_missing"`
}

func (q *Queries) SearchRunners(ctx context.Context, arg SearchRunnersParams) ([]SearchRunnersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchRunners, arg.SearchName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRunnersRow
	for rows.Next() {
		var i SearchRunnersRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.FullName,
			&i.LastTeam,
			&i.BatsLhb,
			&i.PriorSr,
			&i.PriorAtt,
			&i.SprintSpeed,
			&i.SprintSpeedMissing,
			&i.Age,
			&i.AgeMissing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
