// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetModelMeta(ctx context.Context) (GetModelMetaRow, error)
	ListModelCoefficients(ctx context.Context) ([]ModelCoefficient, error)
	ListRE24Cells(ctx context.Context) ([]Re24Cell, error)
	ListWinProbCells(ctx context.Context, tableKind string) ([]WinProbCell, error)
	SearchCatchers(ctx context.Context, arg SearchCatchersParams) ([]SearchCatchersRow, error)
	SearchPitchers(ctx context.Context, arg SearchPitchersParams) ([]SearchPitchersRow, error)
	SearchRunners(ctx context.Context, arg SearchRunnersParams) ([]SearchRunnersRow, error)
}

var _ Querier = (*Queries)(nil)
