// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: re24.sql

package db

import (
	"context"
)

const listRE24Cells = `-- name: ListRE24Cells :many
SELECT base_code, outs, expected_runs FROM re24_cells
`

func (q *Queries) ListRE24Cells(ctx context.Context) ([]Re24Cell, error) {
	rows, err := q.db.QueryContext(ctx, listRE24Cells)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Re24Cell
	for rows.Next() {
		var i Re24Cell
		if err := rows.Scan(&i.BaseCode, &i.Outs, &i.ExpectedRuns); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
