// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: win_prob.sql

package db

import (
	"context"
)

const listWinProbCells = `-- name: ListWinProbCells :many
SELECT table_kind, inning_bucket, half, outs, base_code, score_bucket, win_rate, n
FROM win_prob_cells
WHERE table_kind = ?
`

func (q *Queries) ListWinProbCells(ctx context.Context, tableKind string) ([]WinProbCell, error) {
	rows, err := q.db.QueryContext(ctx, listWinProbCells, tableKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WinProbCell
	for rows.Next() {
		var i WinProbCell
		if err := rows.Scan(
			&i.TableKind,
			&i.InningBucket,
			&i.Half,
			&i.Outs,
			&i.BaseCode,
			&i.ScoreBucket,
			&i.WinRate,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
